Repository MPH-Bali/green-village-project, pull requests merged in 2018-03, with the labels that each got.

#128 fix review comments
  public/src/components/Manager/Delivery/Form.vue
  public/src/components/Manager/Delivery/Table.vue
  public/yarn.lock
  yarn-error.log
Labels: Work In Progress

#176 Feature/realtime charts
  functions/index.js
  functions/package.json
  functions/yarn.lock
Labels: Work In Progress

#170 feature/menu-links
  public/src/components/Manager/Menu/Menu.vue
Labels: question

#127 (merge AFTER demo) Feature/01.0 #34 facility manager login
  public/src/components/Manager/LoadingMask.vue
  public/src/components/Manager/Login/ConfirmationForm.vue
  public/src/components/Manager/Login/Login.vue
  public/src/components/Manager/Login/LoginForm.vue
  public/src/components/Manager/Login/Unapproved.vue
  public/src/components/Manager/Manager.vue
  public/src/components/Manager/Menu/Menu.vue
  public/src/firebase.js
  public/src/firestore.js
  public/src/i18n/en.js
  public/src/main.js
  public/src/router.js
Labels: release
